### ISSUE TITLE
NameError: name 'read_i18n' is not defined

### ISSUE THREAD

**Issue by hirnwunde** [Touch-Night/more_translators#9]
**Describe the bug**
When I activate the extension and then restart text-generation-webui after clicking on "apply flags/extensions and restart", i get the error message

```
Traceback (most recent call last):
  File "C:\prgs\text-generation-webui\modules\extensions.py", line 37, in load_extensions
    extension = importlib.import_module(f"extensions.{name}.script")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\prgs\text-generation-webui\installer_files\env\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\prgs\text-generation-webui\extensions\more_translators\script.py", line 277, in <module>
    settings = load_settings()
               ^^^^^^^^^^^^^^^
  File "C:\prgs\text-generation-webui\extensions\more_translators\script.py", line 269, in load_settings
    print(read_i18n("未找到设置文件translators_settings.yaml，已按默认设置创建。"))
          ^^^^^^^^^
NameError: name 'read_i18n' is not defined
```

The UI of the extension is then not available in the chat tab

**To Reproduce**
install `more_transators` as in [Readme.md](https://github.com/Touch-Night/more_translators/blob/main/README.md)

**Expected behavior**
A UI-Element to use more_translators

**Screenshots**
Nothing to screenshotting ;-)

**Environment:**
 - Python version: 3.11.8
 - text-generation-webui version: snapshot-2024-04-07
 - translators version 5.9.1
 - OS: Windows 11

**Additional context**
Same with downgrade to translators version 5.8.3

**Comment by Touch-Night** [comment]
It looks like I called read_i18n before defining it. It's my fault, will fix it as soon as possible. For a real quick fix if you want to use it right now, you can create translators_settings.yaml file in the more_translators folder with these content:  
```
"activate": True,
"user lang": "auto",
"llm lang": "en",
"i18n lang": "en",
"translator string": "alibaba",
"translate mode": "to-from"
```
and then restart the webui.
